module.exports = {
	// Characters
	ADD_CHARACTER: 'ADD_CHARACTERS',
	REMOVE_CHARACTER: 'REMOVE_CHARACTERS',
	UPDATE_INITIATIVE: 'UPDATE_INITIATIVE',
	UPDATE_HITPOINTS: 'UPDATE_HITPOINTS',
	CHANGE_ACTIVE_CHARACTER: 'CHANGE_ACTIVE_CHARACTER',
	ROLL_INITIATIVES: 'ROLL_INITIATIVES',
	DEAL_DAMAGE: 'DEAL_DAMAGE',
};
